from django.urls import include, path
from .views import *
from .tasks import checksubstatus
from .ot_views.password_management import *
from .ot_views.payroll import *
from .ot_views.acc_management import *
from .ot_views.resignation import *
from .ot_views.chat import *
from .ot_views.attendance import *
from .ot_views.policies import *
from .ot_views.investments import *
from .ot_views.grev_tickets import *
from .ot_views.requests import *
from .ot_views.employee_management import *
from .ot_views.leaves import *
from .ot_views.metrics import *
from .views import (
    HandleImages,
    GethandleImages,
    EmployeesByRole,

    # Document access & verification
    DocumentAccessRuleListCreate,
    AssignedPendingVerifications,
    VerifyDocumentAPIView,
    EmployeeVerificationHistory,
)



# from .views import handleImages 

urlpatterns = [
     # path("gethandleimages/", handleImages.as_view(), name="gethandleimages"),
     path('accountregistration/', AccountRegistrationView.as_view(), name='accountregistration'),
     path('login/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
     path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
     path('get-user-details/', GetUserDetails.as_view(), name='user_details'),
     path('add-organization/', CreateOrganization.as_view(), name='add-organization'),
     path('is-org-created/', IsOrgCreated.as_view(), name='is-org-created'),
     path('is-sub/', IsSubscribed.as_view(), name='is-sub'),
     path('create_super_user/', create_super_user, name='create_super_user'),
     path('create-payment-intent/', create_payment_intent.as_view(), name='create-payment-intent'),
     path('getaccountdetails/', AccountDetails.as_view(), name='getaccountdetails'),
     path('paymentsuccess/', OnPaymentSuccess.as_view(), name='paymentsuccess'),
     
     path('fetchchilds/', fetchChilds.as_view(), name='fetchchilds'),
     path('fetchchild/', fetchChild.as_view(), name='fetchchild'),
     path('createchild/', CreateChild.as_view(), name='createchild'),
     path('createemployee/', CreateEmployee.as_view(), name='createemployee'),
     path('getcreateemployee/', GetCreateEmployee.as_view(), name='getcreateemployee'),
     path('fetchnotifications/', fetchNotifications.as_view()),
     path('fetchnotificationscount/',fetchNotificationsCount.as_view()),

     path('fetchreviewroles/', fetchreviewroles.as_view(), name='fetchreviewroles'),
     path('fetchlaterequests/', fetchlaterequests.as_view(), name='fetchreviewroles'),
     path('fetchroles/', fetchRoles.as_view(), name='fetchroles'),
     path('updaterole/', updateRole.as_view(), name='updaterole'),
     path('updateapproval/', updateApproval.as_view(), name='updateapproval'),
     path('fetchemployees/', fetchEmployees.as_view(), name='fetchemployees'),
     path('addrole/', addRole.as_view(), name='addrole'),
     path('forgotpassword/', ForgotPasswordAPIView.as_view(),name='forgotpassword'),
     path('resetpassword/<uidb64>/<token>/',ResetPasswordAPIView.as_view(), name='resetpassword'),
     path('changepassword/', changePassword.as_view(), name='changepassword'),
     path('orgstructure/', createOrgStructure.as_view(), name='orgstructure'),
     path('fetchapprovals/', fetchApprovals.as_view(), name='fetchapprovals'),
    #  path('departments/', Departments.as_view(), name='departments'),
     path('appraisals/', Appraisal.as_view(), name='appraisals'),
    #  path('designations/', Designations.as_view(), name='designations'),
     path("designations/", GetDesignations.as_view(), name="designations"),
    path("departments/", GetDepartments.as_view(), name="departments"),
     path('fetchdepartments/', FetchDepartments.as_view(), name='fetchdepartments'),
     path('fetchdesignations/', FetchDesignations.as_view(), name='fetchdesignations'),
     path('basicdetails/',basicDetails.as_view(), name='basicdetails'),
     path('bankdetails/',EmployeeBankDetailsAPIView.as_view(), name='bankdetails'),
     path('getbasicdetails/',GetbasicDetails.as_view(), name='getbasicdetails'),
     path('getbankdetails/',GetbankDetails.as_view(), name='getbankdetails'),
     path('getempbirthdays/',GetEmployeeBirthdays.as_view(), name='getempbirthdays'),
     path('cmetrics/',CurrentMonthMetrics.as_view(), name='monthatt'),
     path('bulkupload/',bulkUpload.as_view(), name='bulkupload'),
     path('uploadatt/',UploadAttendance.as_view(), name='uploadatt'),
     path('getattendance/',getAttendance.as_view(), name='getattendance'),
     path('userattendance/',userAttendance.as_view(), name='userattendance'),
     path('attendancerecords/',AttendanceListView.as_view(), name='attendancerecords'),
     path('leavepolicy/',LeavePolicies.as_view(), name='leavepolicy'),
     path('leavepolicy1/',LeavePolicies1.as_view(), name='leavepolicy1'),
     path('payrollpolicy/',payrollpolicies.as_view(), name='leavepolicy'),
     path('leaves/',Leave.as_view(), name='leave'),
     path('update_leaves/', update_leaves, name='update_leaves'),
     path('fetchchildaccounts/', FetchChildAccounts.as_view(), name='fetchchildaccounts'),
     path('leaveapprovals/',fetchLeaveApprovals.as_view(), name='leaveapprovals'),
     path('handleimages/', HandleImages.as_view(), name='handleimages'),
     path('relations/',RelationshipView.as_view(), name='relations'),
     path('getrelations/',GetRelationshipView.as_view(), name='getrelations'),
     path('ged/', gde, name='get_employee_attendance'),
     path('occasions/',OccasionView.as_view(), name='occasions'),
     path('getoccasions/',GetOccasionView.as_view(), name='getoccasions'),
     path('education/',EducationView.as_view(), name='education'),
     path('geteducation/',GetEducationView.as_view(), name='geteducation'),
     path('freetrail/',freeTrail.as_view(),name='freetrail'),
     path('leavebalance/',fetchLeaveBal.as_view(),name='leavebalance'),
     path('verify-token/',VerifyTokenView.as_view(), name='verify-token'),
     path('verify/<str:token>/', verify_email, name='verify_email'),
     path('test/',checksubstatus, name='test'),
     path('addquotes/',QuoteUpload.as_view(), name='addquotes'),
     path('otp/', OtpVerification.as_view(), name='otp'),    
     path('grievances/', GrievanceListCreate.as_view(), name='grievance-list-create'),
     path('tickets/', TicketListCreate.as_view(), name='ticket-list-create'),
     path('grievances/admin/', GrievanceHrList.as_view(), name='grievance-list-hr'),
     path('tickets/admin/', TicketHrList.as_view(), name='ticket-list-hr'),
     path('grievances/<int:pk>/', GrievanceDetail.as_view(), name='grievance-detail'),
     path('tickets/<int:pk>/', TicketDetail.as_view(), name='ticket-detail'),
     path('grievances/<int:grievance_id>/comments/', GrievanceCommentListCreate.as_view(), name='grievance-comments-list-create'),
     path('tickets/<int:ticket_id>/ticketcomments/', TicketCommentListCreate.as_view(), name='grievance-comments-list-create'),
     path('comments/<int:pk>/', GrievanceCommentDetail.as_view(), name='grievance-comment-detail'),      
     path('ticketcomments/<int:pk>/', TicketCommentDetail.as_view(), name='ticket-comment-detail'),      
     path('leavespermonth/',leavesPerMonth,name='leavespermonth'),
     path('payrollinfo/',PayrollInfo.as_view(),name='payrollinfo'),
     path('runpayroll/',PayCalculator.as_view(),name='runpayroll'),
     path('payslip/',PayslipView.as_view(),name='payslipview'),
     path('ipexceptions/',IPExceptionView.as_view(),name='ipexceptions'),
     path('removeip/',IpRestriction.as_view(),name='removeip'),
     path('fetchip/',FetchIP.as_view(),name='fetchip'),
     path('getipexceptions/',GetIPExceptionUsers.as_view(),name='getipexceptions'),
     path('emailpayslip/',PayslipEmailView.as_view(),name='payslipview'),
     path('punchattendance/',AddAttendance.as_view(),name='addattendance'),
     path('addbreak/',AddBreak.as_view(),name='addbreak'),
     path('uploadleavebal/',uploadLeaveBalance.as_view(),name='uploadleavebal'),
     path('attendanceinfo/',AttendanceInfo.as_view(),name='attendanceinfo'),
     path('getholidays/',GetHolidays.as_view(),name='getholidays'),
     path('uploadholidays/',uploadHolidays.as_view(),name='uploadholidays'),
     path('uploadoptholidays/',uploadOptionalHolidays.as_view(),name='uploadoptholidays'),
     path('getips/',IPDetails.as_view(),name='getips'),
     path('setips/',AddIPDetails.as_view(),name='setips'),
     path('attendancerequest/',AttendanceRequest.as_view(),name='attendancerequest'),
     path('comprequest/',CompensationRequest.as_view(),name='comprequest'),
     path('hrcomprequest/',HRCompensationRequest.as_view(),name='comprequest'),
     path('hrcompapprovals/',HRCompApprovals.as_view(),name='comprequest'),
     path('loginrequest/', RMLoginRequests.as_view(), name='lateloginrequest'),
     path('displayrequests/',DisplayAttRequests.as_view(),name='displayrequests'),
     path('displaycompoffrequests/',CompOffRequests.as_view(),name='displaycompoffrequests'),
     path('hrdisplaycompoffrequests/',HRCompOffRequests.as_view(),name='displaycompoffrequests'),
     path('displayloginrequests/',DisplayLoginRequests.as_view(),name='displayloginrequests'),
     path('hrattrequests/',HRAttRequests.as_view(),name='displayrequests'),
     path('hrloginequests/',RMLoginRequests.as_view(),name='rmloginrequests'),
     path('get-years-months/',GetYearsMonths.as_view(),name='displayyearmonths'),
     path('get-avail-years-months/',GetAvailYearsMonths.as_view(),name='displayavailyearmonths'),
     path('greetings/',Greetings.as_view(),name='greetings'),
     path('checktimeout/',CheckTimeOut.as_view(),name='checktimout'),
     path('fetchdaybreaks/',GetDateBreaks.as_view(),name='fetchdaybreaks'),
     path('getquote/',GenerateQuote,name='getquote'),
     path('fetch-attendance-policy/', FetchAttendancePolicy.as_view(), name='fetch_policy'),
     path('fetch-late-login-policy/', FetchLateLoginPolicy.as_view(), name='fetch_late_login_policy'),
     path('attendance-request-policy/', AttendanceRequestPolicyView.as_view(), name='attendance_policy'),
     path('attendance-request-policy/', AttendanceRequestPolicyView.as_view(), name='fetch_policy'),
     path('attendance-request-policy1/', FetchAttendanceReqPolicy.as_view(), name='fetch_policy'),
     path('create-attendance-policy/', CreatePolicyView.as_view(), name='create_policy'),
     path('create-late-login-policy/', CreateLateLoginPolicy.as_view(), name='create_policy'),
     path('pfslabs/', PfSlabsListCreateView.as_view(), name='pfslabs-list-create'),
     path('pfslabs/<uuid:child_id>/', PfSlabsListCreateView.as_view(), name='pfslabs-list-create-child'),
     path('export-payroll/', PayrollCSVExport.as_view(), name='pfslabs-list-create-child'),
     path('pfslab/<uuid:pk>/', PfSlabsDetailView.as_view(), name='pfslabs-detail'),
     path('empdataforrm/',EmpDataForRM.as_view(), name='empdataforrm'),
     path('empdataforhr/',EmpDataForHR.as_view(), name='empdataforhr'),
     path('fetchdept/',FetchDepartments.as_view(), name='fetchdept'),
     path('fetchattrecords/',FetchAttendanceRecords.as_view(), name='fetchattrecords'),
     path('updateattrecord/',UpdateAttendanceRecord.as_view(), name='updateattrecord'),
     path('isrm/',isReportingManager.as_view(), name='fetchdept'),
     path('fetchoptional/',FetchOptionalHolidays.as_view(), name='fetchoptional'),
     path('empoptionalholidays/',EmpOptionalHolidays.as_view(), name='empoptionalholidays'),
     path('optdataforhr/',FetchOptionalHolidaysforHr.as_view(), name='empdataforhr'),
     path('getpresentabs/',getPresentAbsentMonth.as_view(), name='getpresentabs'),
     path('attendancesummary/',AttendanceSummaryView.as_view(), name='attendancesummary'),
     path('allowances/',AllowanceView.as_view(), name='allowances'),
     path('production/allowances/',ProductionAllowanceView.as_view(), name='prod-allowances'),
     path('balanceallowances/',CalculateRem.as_view(), name='balanceallowances'),
     path('onboardemployee/',OnboardEmployee.as_view(), name='onboardemployee'),
     path('prejoinEmployee/',preJoinEmployee.as_view(), name='prejoinemployee'),
     path('onboardemployee/production/',OnboardProdEmployee.as_view(), name='onboardemployee-prod'),
     path('ged/', gde, name='get_employee_attendance'),
     path('createobjs/', createobjs, name='createobjs'),
     path('form12bb/', Form12BBAPIView.as_view()),
     path('myform12bb/', getUserForm12BBView.as_view()),
     path('form12bb/<uuid:form_id>/', Form12BBAPIView.as_view()),
     path('form12bb/<uuid:form_id>/evidence/', EvidenceAPIView.as_view()),
     path('form-12bb/download/<uuid:form_id>/', form_12bb_html, name='form_12bb_html'),
     path('conversations/create/', CreateConversationView.as_view(), name='create_conversation'),
     path('conversations/<uuid:conversation_id>/send/', SendMessageView.as_view(), name='send_message'),
     path('conversations/<uuid:conversation_id>/messages/', GetConversationMessagesView.as_view(), name='get_messages'),
     path('conversations/', RecentConversationsView.as_view(), name='recent_conversations'),
     path('conversationemployees/', EmployeeListView.as_view(), name='employee_list'),
     path('unreadcount/', UnreadConversationsCountView.as_view(), name='unreadcount'),
     path('monthlydata/', MonthlyDataAPIView.as_view(), name='monthlydata-list-create'),
     path('assets/', AssetsView.as_view(), name='assets'),
     path('asset-details', AssetDetailsView.as_view(), name='asset-details'),
     path('employee-assets', EmployeeAssetFormView.as_view(), name='employee-assets'),
     path('resignations/', ResignationView.as_view(), name='resignations'),
     path('resignations/<int:pk>/', ResignationDetailView.as_view(), name='resignation-detail'),
     path('resignations/manager/', ResignationManagerView.as_view(), name='resignations-manager'),
     path('resignations/hr/', UpdateResStatusView.as_view(), name='resignations-hr'),
     path('leaveapprovalflow/', LeaveApprovalFlowView.as_view(), name='approval-flow'),
     path('broadcast/', BroadCastMessageView.as_view(), name='broadcast'),
     path('validateqr', ValidateQR.as_view(), name='validateqr'),
     path('payroll-preview/', DisplayPayrollAPIView.as_view(), name='payroll-preview'),
     path('notify-manager/', NotifyAccountsManagerAPIView.as_view(), name='notify-manager'),
     path('accounts/payroll/preview/', PreviewPayrollAPIView.as_view(), name='accounts-preview'),
     path('getattendancetype/', getAttendanceType.as_view(), name='get-att-type'),
     path('addattendancesingle/', AddAttendanceView.as_view(), name='add_attendance'),
     path('metrics/attendance/', AttendanceMetricsAPIView.as_view(), name='attendance-metrics'),
     path('metrics/attendance/data/', AttendanceDataAPIView.as_view(), name='attendance-data'),
     path('metrics/leaves/pending-requests/', pendingRequests.as_view(), name='pending-requests'),
     path('metrics/leaves/upcoming-leaves/', upComingLeaves.as_view(), name='upcoming-leaves'),
     path('certifications/', CertificationsView.as_view(), name="certifications"),
     path('skills/', SkillsView.as_view(), name="skills"),
     path('getexperience/',GetExperienceView.as_view(), name='getexperience'),
     path('experience/',ExperienceView.as_view(), name='experience'),
     path("docaccessrules/", DocumentAccessRuleListCreate.as_view()),
     path("docaccessrules/<uuid:id>/", DocumentAccessRuleDetail.as_view()),
     path('assigned-pending/', AssignedPendingVerifications.as_view(),name='assigned_pending_verifications'),
     path('verify-document/',VerifyDocumentAPIView.as_view(),name='verify_document'),
     path('employee-verification-history/<uuid:employee_id>/',EmployeeVerificationHistory.as_view(),name='employee_verification_history'),
     path('employees-by-role/', EmployeesByRole.as_view(),name='employees_by_role'),
     path('handle-images/',HandleImages.as_view(), name='handle_images'),
    # path("handle-images/", HandleImages.as_view()),

     path('get-handle-images/',GethandleImages.as_view(),name='get_handle_images'),
     path("allowed-actions/",AllowedActionsByRole.as_view(),name="allowed_actions_by_role"),
     path("my-doc-verification-status/", MyDocumentVerificationStatus.as_view()),
     path("my-roles/", MyRoles.as_view()),
     path(
    "update-document-verification/",
    UpdateDocumentVerification.as_view()
),

     path("employees-in-org/", AllEmployeesInOrg.as_view(), name="employees_in_org"),
     path("send-rejection-summary/", SendRejectionSummary.as_view()),

]