# Generated by Django 4.2.7 on 2024-05-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0002_alter_organization_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeexperience',
            name='attach_relieving_letter',
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='relieving_letter',
            field=models.ImageField(blank=True, null=True, upload_to='RelievngLetterImages'),
        ),
        migrations.AlterField(
            model_name='document',
            name='aadhar',
            field=models.ImageField(blank=True, null=True, upload_to='Aadhaars'),
        ),
        migrations.AlterField(
            model_name='document',
            name='offerLetter',
            field=models.ImageField(blank=True, null=True, upload_to='OfferLetters'),
        ),
        migrations.AlterField(
            model_name='document',
            name='panCard',
            field=models.ImageField(blank=True, null=True, upload_to='PanCards'),
        ),
        migrations.AlterField(
            model_name='document',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='Profiles'),
        ),
        migrations.AlterField(
            model_name='employeeeducationdetails',
            name='education_proof',
            field=models.ImageField(blank=True, null=True, upload_to='EducationProof'),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='payslip_1',
            field=models.ImageField(blank=True, null=True, upload_to='Payslips'),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='payslip_2',
            field=models.ImageField(blank=True, null=True, upload_to='Payslips'),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='payslip_3',
            field=models.ImageField(blank=True, null=True, upload_to='Payslips'),
        ),
    ]
