# Generated by Django 4.2.7 on 2024-05-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0003_remove_employeeexperience_attach_relieving_letter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleaves',
            name='advance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeleaves',
            name='bonus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeleaves',
            name='leaves',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeleaves',
            name='lop',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
