# Generated by Django 4.2.7 on 2024-05-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0004_alter_employeeleaves_advance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleaves',
            name='advance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employeeleaves',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employeeleaves',
            name='leaves',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employeeleaves',
            name='lop',
            field=models.IntegerField(default=0),
        ),
    ]
