# Generated by Django 4.1.4 on 2024-05-29 08:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0005_alter_employeeleaves_advance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('net_time_in', models.CharField(blank=True, max_length=8, null=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payrollapp.childaccount')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.employee')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payrollapp.organization')),
            ],
        ),
    ]
