# Generated by Django 4.1.4 on 2024-05-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0006_breaktime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='net_time_in',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breaktime',
            name='net_time_in',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
