# Generated by Django 4.1.4 on 2024-05-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0007_alter_attendance_net_time_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='net_time_in',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='breaktime',
            name='net_time_in',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
