# Generated by Django 4.1.4 on 2024-05-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0008_alter_attendance_net_time_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breaktime',
            name='reason',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
    ]
