# Generated by Django 4.1.4 on 2024-05-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0009_breaktime_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='net_break',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
