# Generated by Django 4.1.4 on 2024-05-31 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0010_attendance_net_break'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holidays',
            old_name='Child_ID',
            new_name='child',
        ),
        migrations.RenameField(
            model_name='holidays',
            old_name='Parent_ID',
            new_name='parent',
        ),
    ]
