# Generated by Django 4.1.4 on 2024-06-04 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0011_rename_child_id_holidays_child_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LateLoginRequestObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=250)),
                ('Date', models.DateField(default='2024-05-10')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('underreview', 'Under Review')], default='underreview', max_length=15)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payrollapp.childaccount')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='payrollapp.employee')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.organization')),
                ('reported_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='payrollapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LateLoginPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_late_logins', models.IntegerField(default=0)),
                ('no_of_hours', models.CharField(blank=True, max_length=2, null=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payrollapp.childaccount')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRequestPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_requests', models.IntegerField(default=0)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payrollapp.childaccount')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officeStartTime', models.TimeField(blank=True, null=True)),
                ('officeEndTime', models.TimeField(blank=True, null=True)),
                ('workingDays', models.CharField(blank=True, max_length=200, null=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payrollapp.childaccount')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.organization')),
            ],
        ),
    ]
