# Generated by Django 4.1.4 on 2024-06-05 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0012_lateloginrequestobject_lateloginpolicy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('underreview', 'Under Review')], default='underreview', max_length=15)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.employee')),
            ],
        ),
    ]
