# Generated by Django 4.1.4 on 2024-06-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0013_iprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeexperience',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
