# Generated by Django 4.1.4 on 2024-06-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0014_alter_employeeexperience_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='commentsonstatuschange',
            field=models.TextField(blank=True, null=True),
        ),
    ]
