# Generated by Django 4.1.4 on 2024-06-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0017_compoffrequestobject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compoffrequestobject',
            name='status',
        ),
        migrations.AddField(
            model_name='compoffrequestobject',
            name='hrstatus',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('underreview', 'Under Review')], default='underreview', max_length=15),
        ),
        migrations.AddField(
            model_name='compoffrequestobject',
            name='managerstatus',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('underreview', 'Under Review')], default='underreview', max_length=15),
        ),
    ]
