# Generated by Django 4.1.4 on 2024-06-13 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0018_remove_compoffrequestobject_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoffrequestobject',
            name='approvedbyhr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvedbyhr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compoffrequestobject',
            name='approvedbyrm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvedbyrm', to=settings.AUTH_USER_MODEL),
        ),
    ]
