# Generated by Django 4.1.4 on 2024-06-17 08:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0019_compoffrequestobject_approvedbyhr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPExceptions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payrollapp.employee')),
            ],
        ),
    ]
