# Generated by Django 4.1.4 on 2024-06-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0021_ipexceptions_addedby_ipexceptions_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollpolicy',
            name='is_esi_applicable',
            field=models.BooleanField(default=False),
        ),
    ]
