# Generated by Django 4.1.4 on 2024-06-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0022_payrollpolicy_is_esi_applicable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeepayroll',
            old_name='ctc',
            new_name='gross',
        ),
    ]
