# Generated by Django 4.1.4 on 2024-06-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0023_rename_ctc_employeepayroll_gross'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollpolicy',
            name='basic_percentage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
