# Generated by Django 4.1.4 on 2024-06-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0024_payrollpolicy_basic_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollpolicy',
            name='is_esi_applicable',
        ),
        migrations.AddField(
            model_name='payrollpolicy',
            name='esi_percentage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
