# Generated by Django 4.1.4 on 2024-06-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0025_remove_payrollpolicy_is_esi_applicable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollpolicy',
            name='esi_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
