# Generated by Django 4.1.4 on 2024-06-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0026_alter_payrollpolicy_esi_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollpolicy',
            name='employer_esi_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrollpolicy',
            name='employer_pf_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payrollpolicy',
            name='basic_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='payrollpolicy',
            name='da_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='payrollpolicy',
            name='hra_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='payrollpolicy',
            name='pf_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
