# Generated by Django 4.1.4 on 2024-06-18 11:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0027_payrollpolicy_employer_esi_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childaccount',
            name='PFType',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('slab', 'Slab')], default='fixed', max_length=15),
        ),
        migrations.CreateModel(
            name='PfSlabs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('end_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf_amount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('unit', models.CharField(choices=[('percent', 'Percentage'), ('amount', 'Amount')], max_length=20)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payrollapp.childaccount')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.organization')),
            ],
        ),
    ]
