# Generated by Django 4.1.4 on 2024-06-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0028_childaccount_pftype_pfslabs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfslabs',
            name='pf_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
