# Generated by Django 4.1.4 on 2024-06-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0029_alter_pfslabs_pf_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayroll',
            name='employer_esi',
            field=models.DecimalField(decimal_places=2, default=3.25, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='employer_pf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
