# Generated by Django 4.1.4 on 2024-06-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0030_employeepayroll_employer_esi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='jobdescription',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='kras',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
    ]
