# Generated by Django 4.1.4 on 2024-06-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0031_employee_jobdescription_employee_kras'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('ontime', 'OnTime'), ('latelogin', 'LateLogin')], default='ontime', max_length=20),
        ),
    ]
