# Generated by Django 4.1.4 on 2024-06-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0032_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
