# Generated by Django 4.1.4 on 2024-06-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0033_leaves_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='careerpath',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
    ]
