# Generated by Django 4.1.4 on 2024-06-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0034_employee_careerpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='duration',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='type',
            field=models.CharField(choices=[('halfday', 'Halfday'), ('fullday', 'Fullday')], default='fullday', max_length=20),
        ),
    ]
