# Generated by Django 4.1.4 on 2024-06-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0035_alter_leaves_duration_alter_leaves_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='leavetype',
            field=models.CharField(choices=[('halfday', 'Halfday'), ('fullday', 'Fullday')], default='fullday', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
