# Generated by Django 4.1.4 on 2024-06-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0036_leaves_leavetype_alter_leaves_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepayroll',
            name='no_leaves',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
