# Generated by Django 4.1.4 on 2024-06-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0037_alter_employeepayroll_no_leaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleaves',
            name='leaves',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
