# Generated by Django 4.1.4 on 2024-06-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0038_alter_employeeleaves_leaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleaves',
            name='leaves',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
