# Generated by Django 4.1.4 on 2024-06-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0039_alter_employeeleaves_leaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('ontime', 'On Time'), ('latelogin', 'Late Login')], default='ontime', max_length=20),
        ),
    ]
