# Generated by Django 4.1.4 on 2024-06-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0041_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='logged_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('ontime', 'On Time'), ('latelogin', 'Late Login')], default='ontime', max_length=20),
        ),
    ]
