# Generated by Django 4.1.4 on 2024-06-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0041_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='quote',
            field=models.TextField(blank=True, max_length=50000000, null=True),
        ),
    ]
