# Generated by Django 4.1.4 on 2024-06-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0042_attendance_logged_in_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('ontime', 'On Time'), ('latelogin', 'Late Login'), ('none', 'None')], default='ontime', max_length=20),
        ),
    ]
