# Generated by Django 4.1.4 on 2024-06-26 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0043_alter_attendance_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaves',
            old_name='type',
            new_name='ttype',
        ),
    ]
