# Generated by Django 4.1.4 on 2024-06-26 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0044_rename_type_leaves_ttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaves',
            old_name='ttype',
            new_name='type',
        ),
    ]
