# Generated by Django 4.1.4 on 2024-06-26 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0045_rename_ttype_leaves_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaves',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='leaves',
            name='type',
        ),
    ]
