# Generated by Django 4.1.4 on 2024-06-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0046_remove_leaves_duration_remove_leaves_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='type',
            field=models.CharField(default='none', max_length=20),
            preserve_default=False,
        ),
    ]
