# Generated by Django 4.1.4 on 2024-06-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0047_leaves_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='durationn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
