# Generated by Django 4.2.7 on 2024-06-27 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0042_organization_quote'),
        ('payrollapp', '0048_leaves_durationn'),
    ]

    operations = [
    ]
