# Generated by Django 4.1.4 on 2024-07-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0049_merge_0042_organization_quote_0048_leaves_durationn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='leave_balance',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
