# Generated by Django 4.1.4 on 2024-07-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0050_alter_leavebalance_leave_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleaves',
            name='lop',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employeepayroll',
            name='lop',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
