# Generated by Django 4.1.4 on 2024-07-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0051_alter_employeeleaves_lop_alter_employeepayroll_lop'),
    ]

    operations = [
        migrations.AddField(
            model_name='childaccount',
            name='iprestriction',
            field=models.BooleanField(default=True),
        ),
    ]
