# Generated by Django 4.1.4 on 2024-07-09 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0052_childaccount_iprestriction'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionalHolidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payrollapp.childaccount')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.organization')),
            ],
        ),
    ]
