# Generated by Django 4.1.4 on 2024-07-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0055_employeeoptholiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('latelogin', 'Late Login'), ('halfday', 'Half Day'), ('absent', 'Absent'), ('leave', 'Leave'), ('holiday', 'Holiday')], default='present', max_length=20),
        ),
    ]
