# Generated by Django 4.1.4 on 2024-08-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0056_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlydata',
            name='month',
            field=models.IntegerField(default='07'),
        ),
        migrations.AlterField(
            model_name='monthlydata',
            name='year',
            field=models.IntegerField(default='2024'),
        ),
    ]
