# Generated by Django 4.1.4 on 2024-08-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0057_alter_monthlydata_month_alter_monthlydata_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlydata',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monthlydata',
            name='year',
            field=models.IntegerField(),
        ),
    ]
