# Generated by Django 4.1.4 on 2024-08-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0058_leavebalance_month_leavebalance_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavebalance',
            name='leave_balance',
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='carry_forwarded_leave_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='current_leave_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
