# Generated by Django 4.1.4 on 2024-08-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0059_remove_leavebalance_leave_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='advance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
    ]
