# Generated by Django 4.1.4 on 2024-08-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0060_leavebalance_advance_leavebalance_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='lop',
            field=models.IntegerField(default=0),
        ),
    ]
