# Generated by Django 4.1.4 on 2024-08-13 08:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0061_leavebalance_lop'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddr',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='ipdata',
            name='ipaddresses',
        ),
        migrations.AddField(
            model_name='ipdata',
            name='ipaddresses',
            field=models.ManyToManyField(related_name='ip_data', to='payrollapp.ipaddr'),
        ),
    ]
