# Generated by Django 4.1.4 on 2024-09-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0062_ipaddr_remove_ipdata_ipaddresses_ipdata_ipaddresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepolicy',
            name='min_working_for_full_day',
            field=models.DecimalField(blank=True, decimal_places=1, default=4.5, max_digits=4, null=True),
        ),
    ]
