# Generated by Django 4.1.4 on 2024-09-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0063_attendancepolicy_min_working_for_full_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pfdeclaration',
            field=models.ImageField(blank=True, null=True, upload_to='pfDeclaration'),
        ),
    ]
