# Generated by Django 4.1.4 on 2024-09-10 04:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0064_document_pfdeclaration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=3)),
                ('child', models.ManyToManyField(blank=True, null=True, related_name='allo_child', to='payrollapp.childaccount')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.organization')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allowance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.allowance')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_allowances', to='payrollapp.employeepayroll')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allowance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.allowance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_allowances', to='payrollapp.employee')),
            ],
        ),
    ]
