# Generated by Django 4.1.4 on 2024-09-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0065_allowance_payrollallowance_employeeallowance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='min_value',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
