# Generated by Django 4.1.4 on 2024-09-10 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0066_alter_allowance_min_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='min_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
        migrations.CreateModel(
            name='EmployeePay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctc', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gross', models.DecimalField(decimal_places=2, max_digits=15)),
                ('basic', models.DecimalField(decimal_places=2, max_digits=15)),
                ('employer_pf', models.DecimalField(decimal_places=2, max_digits=15)),
                ('employer_esi', models.DecimalField(decimal_places=2, max_digits=15)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_pays', to='payrollapp.employee')),
            ],
        ),
    ]
