# Generated by Django 4.1.4 on 2024-09-11 05:47

from django.db import migrations, models
import django.db.models.deletion
import payrollapp.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0067_alter_allowance_min_value_employeepay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form12BB',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('pan', models.CharField(max_length=10)),
                ('financial_year', models.CharField(max_length=9)),
                ('rent_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('landlord_name', models.CharField(max_length=255)),
                ('landlord_address', models.TextField()),
                ('landlord_pan', models.CharField(blank=True, max_length=10, null=True)),
                ('leave_travel_conesssions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lender_name', models.CharField(max_length=255)),
                ('lender_address', models.TextField()),
                ('lender_pan', models.CharField(blank=True, max_length=10, null=True)),
                ('section_80c', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('section_80ccc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('section_80ccd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('section_80d', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('section_80e_interest_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('section_80g_donation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('section_80tta_interest_earned', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('place', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hra', models.FileField(upload_to=payrollapp.models.evidence_upload_path)),
                ('leave_travel_consession', models.FileField(upload_to=payrollapp.models.evidence_upload_path)),
                ('interest_paid', models.FileField(upload_to=payrollapp.models.evidence_upload_path)),
                ('section_80c', models.FileField(upload_to=payrollapp.models.evidence_upload_path)),
                ('section_80ccc', models.FileField(upload_to=payrollapp.models.evidence_upload_path)),
                ('section_80ccd', models.FileField(upload_to=payrollapp.models.evidence_upload_path)),
                ('section_80d', models.FileField(upload_to=payrollapp.models.evidence_upload_path)),
                ('section_80e_interest_paid', models.FileField(upload_to=payrollapp.models.evidence_upload_path)),
                ('section_80g_donation_amount', models.FileField(upload_to=payrollapp.models.evidence_upload_path)),
                ('section_80tta_interest_earned', models.FileField(upload_to=payrollapp.models.evidence_upload_path)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.employee')),
                ('form_12bb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='payrollapp.form12bb')),
            ],
        ),
    ]
