# Generated by Django 4.1.4 on 2024-09-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0068_form12bb_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='form12bb',
            name='employee_addr',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
