# Generated by Django 4.1.4 on 2024-09-11 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0069_form12bb_employee_addr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form12bb',
            old_name='employee_addr',
            new_name='employee_address',
        ),
    ]
