# Generated by Django 4.1.4 on 2024-09-12 12:15

from django.db import migrations, models
import payrollapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0070_rename_employee_addr_form12bb_employee_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='hra',
            field=models.FileField(blank=True, null=True, upload_to=payrollapp.models.evidence_upload_path),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='interest_paid',
            field=models.FileField(blank=True, null=True, upload_to=payrollapp.models.evidence_upload_path),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='leave_travel_consession',
            field=models.FileField(blank=True, null=True, upload_to=payrollapp.models.evidence_upload_path),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='section_80c',
            field=models.FileField(blank=True, null=True, upload_to=payrollapp.models.evidence_upload_path),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='section_80ccc',
            field=models.FileField(blank=True, null=True, upload_to=payrollapp.models.evidence_upload_path),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='section_80ccd',
            field=models.FileField(blank=True, null=True, upload_to=payrollapp.models.evidence_upload_path),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='section_80d',
            field=models.FileField(blank=True, null=True, upload_to=payrollapp.models.evidence_upload_path),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='section_80e_interest_paid',
            field=models.FileField(blank=True, null=True, upload_to=payrollapp.models.evidence_upload_path),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='section_80g_donation_amount',
            field=models.FileField(blank=True, null=True, upload_to=payrollapp.models.evidence_upload_path),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='section_80tta_interest_earned',
            field=models.FileField(blank=True, null=True, upload_to=payrollapp.models.evidence_upload_path),
        ),
    ]
