# Generated by Django 4.1.4 on 2024-09-18 06:27

from django.db import migrations
import payrollapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0073_message_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=payrollapp.models.EncryptedTextField(),
        ),
    ]
