# Generated by Django 4.1.4 on 2024-09-18 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0074_alter_message_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
