# Generated by Django 4.1.4 on 2024-09-18 06:38

from django.db import migrations, models
import django.db.models.deletion
import payrollapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0075_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', payrollapp.models.EncryptedTextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='payrollapp.conversation')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_msg', to='payrollapp.employee')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.employee')),
            ],
        ),
    ]
