# Generated by Django 4.1.4 on 2024-09-18 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0080_alter_message_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 18, 9, 29, 47, 232847, tzinfo=datetime.timezone.utc)),
        ),
    ]
