# Generated by Django 4.1.4 on 2024-09-18 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0081_alter_message_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
