# Generated by Django 4.1.4 on 2024-09-18 09:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
import payrollapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0082_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', payrollapp.models.EncryptedTextField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2024, 9, 18, 9, 31, 6, 619244, tzinfo=datetime.timezone.utc))),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='payrollapp.conversation')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_msg', to='payrollapp.employee')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.employee')),
            ],
        ),
    ]
