# Generated by Django 4.1.4 on 2024-09-18 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0083_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='message',
            name='timestampp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 18, 9, 34, 35, 793944, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
