# Generated by Django 4.1.4 on 2024-09-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0085_conversation_is_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeepayroll',
            name='da',
        ),
        migrations.RemoveField(
            model_name='employeepayroll',
            name='hra',
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='allowances',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
