# Generated by Django 4.1.4 on 2024-09-27 09:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0086_remove_employeepayroll_da_remove_employeepayroll_hra_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeassetform',
            old_name='employeeID',
            new_name='employee',
        ),
        migrations.RemoveField(
            model_name='employeeassetform',
            name='AssetIssueDate',
        ),
        migrations.RemoveField(
            model_name='employeeassetform',
            name='EmployeeJoinDate',
        ),
        migrations.RemoveField(
            model_name='employeeassetform',
            name='assetTypeandConfiguration',
        ),
        migrations.RemoveField(
            model_name='employeeassetform',
            name='asset_serial_number',
        ),
        migrations.RemoveField(
            model_name='employeeassetform',
            name='asset_type',
        ),
        migrations.AddField(
            model_name='employeeassetform',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeassetform',
            name='issuedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_issued_by', to='payrollapp.employee'),
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payrollapp.childaccount')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payrollapp.department')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AssetDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('configuration', models.TextField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.assets')),
            ],
        ),
    ]
