# Generated by Django 4.1.4 on 2024-09-27 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0088_alter_assetdetails_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeassetform',
            name='assetdetails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payrollapp.assetdetails'),
        ),
        migrations.AddField(
            model_name='employeeassetform',
            name='is_issues',
            field=models.BooleanField(default=False),
        ),
    ]
