# Generated by Django 4.1.4 on 2024-09-27 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0089_employeeassetform_assetdetails_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeassetform',
            old_name='is_issues',
            new_name='is_issued',
        ),
    ]
