# Generated by Django 4.1.4 on 2024-09-30 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0090_rename_is_issues_employeeassetform_is_issued'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('noticeperiodtill', models.DateField()),
                ('handoverings', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('rm_comments', models.TextField(blank=True, null=True)),
                ('hr_comments', models.TextField(blank=True, null=True)),
                ('bo_comments', models.TextField(blank=True, null=True)),
                ('bo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bo', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.employee')),
                ('hr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr', to=settings.AUTH_USER_MODEL)),
                ('rm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
