# Generated by Django 4.1.4 on 2024-10-07 12:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0092_alter_resignation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApprovalFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('days', models.IntegerField()),
                ('level', models.IntegerField()),
                ('leaveForwarding', models.BooleanField(default=False)),
                ('leaveForwardingUpto', models.CharField(choices=[('HR', 'HR'), ('Business Owner', 'Business Owner'), ('Reporting Manager', 'Reporting Manager')], default='HR', max_length=20)),
                ('approvingPerson', models.CharField(choices=[('HR', 'HR'), ('Reporting Manager', 'Reporting Manager')], default='HR', max_length=20)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payrollapp.childaccount')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.organization')),
            ],
        ),
    ]
