# Generated by Django 4.1.4 on 2024-10-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0093_leaveapprovalflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapprovalflow',
            name='leaveForwarAfer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
