# Generated by Django 4.1.4 on 2024-10-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0094_leaveapprovalflow_leaveforwarafer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
