# Generated by Django 4.1.4 on 2024-10-08 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0095_alter_leaves_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveapprovalflow',
            old_name='leaveForwarAfer',
            new_name='leaveForwardAfter',
        ),
    ]
