# Generated by Django 4.1.4 on 2024-10-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0096_rename_leaveforwarafer_leaveapprovalflow_leaveforwardafter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapprovalflow',
            name='leaveForwardAfter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapprovalflow',
            name='leaveForwardingUpto',
            field=models.CharField(blank=True, choices=[('HR', 'HR'), ('Business Owner', 'Business Owner'), ('Reporting Manager', 'Reporting Manager')], max_length=20, null=True),
        ),
    ]
