# Generated by Django 4.1.4 on 2024-10-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0097_alter_leaveapprovalflow_leaveforwardafter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapprovalflow',
            name='leaveForwardAfter',
        ),
        migrations.RemoveField(
            model_name='leaveapprovalflow',
            name='leaveForwarding',
        ),
        migrations.RemoveField(
            model_name='leaveapprovalflow',
            name='leaveForwardingUpto',
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='leaveForwardAfter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='leaveForwarding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='leaveForwardingUpto',
            field=models.CharField(blank=True, choices=[('HR', 'HR'), ('Business Owner', 'Business Owner'), ('Reporting Manager', 'Reporting Manager')], max_length=20, null=True),
        ),
    ]
