# Generated by Django 4.1.4 on 2024-10-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0098_remove_leaveapprovalflow_leaveforwardafter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavepolicy',
            name='autoApproval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='autoApprovalBefore',
            field=models.IntegerField(default=24),
            preserve_default=False,
        ),
    ]
