# Generated by Django 4.1.4 on 2024-10-15 05:26

from django.db import migrations, models
import django.db.models.deletion
import payrollapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0099_leavepolicy_autoapproval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavepolicy',
            name='autoApprovalBefore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BroadcastCommunications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', payrollapp.models.EncryptedTextField()),
                ('timestampp', models.DateTimeField()),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payrollapp.childaccount')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.organization')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.employee')),
            ],
        ),
    ]
