# Generated by Django 4.1.4 on 2024-10-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0100_alter_leavepolicy_autoapprovalbefore_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollpolicy',
            name='basic_percentage',
        ),
        migrations.RemoveField(
            model_name='payrollpolicy',
            name='da_percentage',
        ),
        migrations.RemoveField(
            model_name='payrollpolicy',
            name='employer_esi_percentage',
        ),
        migrations.RemoveField(
            model_name='payrollpolicy',
            name='employer_pf_percentage',
        ),
        migrations.RemoveField(
            model_name='payrollpolicy',
            name='esi_percentage',
        ),
        migrations.RemoveField(
            model_name='payrollpolicy',
            name='hra_percentage',
        ),
        migrations.RemoveField(
            model_name='payrollpolicy',
            name='pf_percentage',
        ),
        migrations.AddField(
            model_name='payrollpolicy',
            name='payslipHeaderAddress',
            field=models.CharField(default="403, LN's Sri-Nivas Naik's Estates Road no: 1, behind Axis Bank, Motilal Nehru Nagar, Begumpet, Hyderabad, Telangana 500016", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrollpolicy',
            name='payslipHeaderCompany',
            field=models.CharField(default='GA Digital Solutions', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrollpolicy',
            name='payslipHeadertagline',
            field=models.CharField(default='A Business Division of Gunnam Associates', max_length=255),
            preserve_default=False,
        ),
    ]
