# Generated by Django 4.1.4 on 2024-10-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0101_remove_payrollpolicy_basic_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollpolicy',
            name='payslipHeaderlogo',
            field=models.ImageField(blank=True, null=True, upload_to='payslipheaderlogo'),
        ),
    ]
