# Generated by Django 4.1.4 on 2024-10-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0102_payrollpolicy_payslipheaderlogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollpolicy',
            name='payslipHeadertagline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
