# Generated by Django 4.1.4 on 2024-10-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0103_alter_payrollpolicy_payslipheadertagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebankdetails',
            name='bankAcNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
