# Generated by Django 4.1.4 on 2024-11-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0104_alter_employeebankdetails_bankacno'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebankdetails',
            name='ifsc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
