# Generated by Django 4.1.4 on 2024-11-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0105_employeebankdetails_ifsc'),
    ]

    operations = [
        migrations.AddField(
            model_name='childaccount',
            name='acc_type',
            field=models.CharField(choices=[('In House', 'In House'), ('Third Party', 'Third Party')], default='In House', max_length=15),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='status',
            field=models.CharField(choices=[('Preview', 'Preview'), ('Approved', 'Approved'), ('Processed', 'Processed')], default='Preview', max_length=55),
        ),
        migrations.AlterField(
            model_name='childaccount',
            name='iprestriction',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
