# Generated by Django 4.2.7 on 2025-01-22 06:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0106_childaccount_acc_type_employeepayroll_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionAllowances',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('type', models.CharField(choices=[('allowance', 'Allowance'), ('deduction', 'Deduction')], max_length=25)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proallo_chi', to='payrollapp.childaccount')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.organization')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_type',
            field=models.CharField(choices=[('Blue-Collar', 'Blue-Collar'), ('White-Collar', 'White-Collar')], default='White-Collar', max_length=15),
        ),
        migrations.CreateModel(
            name='ProductionPayrollPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowance', models.ManyToManyField(blank=True, null=True, related_name='proallo', to='payrollapp.productionallowances')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payrollapp.childaccount')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.organization')),
            ],
        ),
    ]
