# Generated by Django 4.2.7 on 2025-01-22 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0108_employee_labour_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductionPayrollPolicy',
        ),
    ]
