# Generated by Django 4.2.7 on 2025-01-22 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0109_delete_productionpayrollpolicy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowance',
            name='child',
        ),
        migrations.RenameModel(
            old_name='ProductionAllowances',
            new_name='ProductionAllowance',
        ),
        migrations.CreateModel(
            name='EmployeeProdAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allowance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.productionallowance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_employee_allowances', to='payrollapp.employee')),
            ],
        ),
        migrations.AddField(
            model_name='allowance',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allo_child', to='payrollapp.childaccount'),
        ),
    ]
