# Generated by Django 4.2.7 on 2025-01-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0110_remove_allowance_child_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionallowance',
            name='max_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productionallowance',
            name='min_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
