# Generated by Django 4.2.7 on 2025-01-22 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0111_alter_productionallowance_max_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdEmployeePay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_day_wage', models.DecimalField(decimal_places=2, max_digits=15)),
                ('employer_pf', models.DecimalField(decimal_places=2, max_digits=15)),
                ('employer_esi', models.DecimalField(decimal_places=2, max_digits=15)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_employee_pays', to='payrollapp.employee')),
            ],
        ),
    ]
