# Generated by Django 4.2.7 on 2025-01-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0112_prodemployeepay'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayroll',
            name='deductions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='present',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='prodemployeepay',
            name='employee_esi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prodemployeepay',
            name='employee_pf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeepayroll',
            name='allowances',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
