# Generated by Django 4.1.4 on 2025-01-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0113_employeepayroll_deductions_employeepayroll_present_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='aadhar',
            field=models.FileField(blank=True, null=True, upload_to='Aadhaars'),
        ),
        migrations.AlterField(
            model_name='document',
            name='offerLetter',
            field=models.FileField(blank=True, null=True, upload_to='OfferLetters'),
        ),
        migrations.AlterField(
            model_name='document',
            name='panCard',
            field=models.FileField(blank=True, null=True, upload_to='PanCards'),
        ),
        migrations.AlterField(
            model_name='document',
            name='pfdeclaration',
            field=models.FileField(blank=True, null=True, upload_to='pfDeclaration'),
        ),
    ]
