# Generated by Django 4.1.4 on 2025-02-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0114_alter_document_aadhar_alter_document_offerletter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('onroll', 'Onroll'), ('exit', 'exit'), ('prejoining', 'prejoining')], default='onroll', max_length=15),
        ),
    ]
