# Generated by Django 4.1.4 on 2025-02-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0115_alter_employee_ctc_alter_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidays',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='optionalholidays',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
