# Generated by Django 4.2.7 on 2025-11-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0116_alter_holidays_name_alter_optionalholidays_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='esi_card',
            field=models.FileField(blank=True, null=True, upload_to='esi_cards/'),
        ),
    ]
