# Generated by Django 4.2.7 on 2025-12-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0117_document_esi_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebasicdetails',
            name='contactNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employeebasicdetails',
            name='emergencyContactNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
