# Generated by Django 4.2.7 on 2025-12-04 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0119_employeeskills_employeecertifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeskills',
            old_name='proficiency_level',
            new_name='level',
        ),
        migrations.RemoveField(
            model_name='employeecertifications',
            name='issuing_authority',
        ),
    ]
