# Generated by Django 4.2.7 on 2025-12-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0120_rename_proficiency_level_employeeskills_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecertifications',
            name='issuing_authority',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
