# Generated by Django 4.2.7 on 2025-12-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0121_employeecertifications_issuing_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeexperience',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='previous_positions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='promotions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='role_changes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='transfers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='relieving_letter',
            field=models.ImageField(blank=True, null=True, upload_to='RelievingLetterImages'),
        ),
    ]
