# Generated by Django 4.2.7 on 2025-12-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0122_employeeexperience_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeeducationdetails',
            name='education_proof',
            field=models.FileField(blank=True, null=True, upload_to='education/'),
        ),
    ]
