# Generated by Django 4.2.7 on 2025-12-11 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0123_alter_employeeeducationdetails_education_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('profile', 'Profile'), ('aadhar', 'Aadhaar'), ('panCard', 'PAN Card'), ('offerLetter', 'Offer Letter'), ('pfdeclaration', 'PF Declaration'), ('esi_card', 'ESI Card')], max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=16)),
                ('comment', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_verifications', to='payrollapp.employee')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-verified_at', '-created_at'],
                'unique_together': {('employee', 'document_type')},
            },
        ),
        migrations.CreateModel(
            name='RejectedDocumentArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('file_name', models.CharField(blank=True, max_length=512, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='payrollapp.documentverification')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentFreezeFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_frozen', models.BooleanField(default=False)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_freeze_flag', to='payrollapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentAccessRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=200)),
                ('access', models.CharField(choices=[('Access', 'Access'), ('Deny', 'Deny')], default='Access', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_for_verification', to='payrollapp.employee')),
            ],
            options={
                'unique_together': {('role', 'employee')},
            },
        ),
    ]
