# Generated by Django 4.2.7 on 2025-12-11 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0124_documentverification_rejecteddocumentarchive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rejecteddocumentarchive',
            name='verification',
        ),
        migrations.AlterModelOptions(
            name='documentverification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='documentaccessrule',
            old_name='assigned_by',
            new_name='created_by',
        ),
        migrations.AlterUniqueTogether(
            name='documentaccessrule',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='documentverification',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='documentaccessrule',
            name='function',
            field=models.CharField(default='Document Verification', max_length=200),
        ),
        migrations.AddField(
            model_name='documentaccessrule',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payrollapp.organization'),
        ),
        migrations.AddField(
            model_name='documentaccessrule',
            name='specific_action',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='documentaccessrule',
            name='target_employee',
            field=models.ForeignKey(blank=True, help_text='Optional - if set, rule applies only for this employee', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payrollapp.employee'),
        ),
        migrations.AddField(
            model_name='documentverification',
            name='assigned_role',
            field=models.CharField(blank=True, help_text='Role that performed the verification (useful for audit)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentaccessrule',
            name='access',
            field=models.CharField(default='Access', max_length=50),
        ),
        migrations.AlterField(
            model_name='documentaccessrule',
            name='role',
            field=models.CharField(choices=[('HR_Admin', 'HR_Admin'), ('Manager', 'Manager'), ('IT_Manager', 'IT_Manager'), ('Talent Manager', 'Talent Manager'), ('HR_Assistant', 'HR_Assistant')], max_length=100),
        ),
        migrations.AlterField(
            model_name='documentverification',
            name='document_type',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='documentverification',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_verifications', to='payrollapp.employee'),
        ),
        migrations.AlterField(
            model_name='documentverification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentverification',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DocumentFreezeFlag',
        ),
        migrations.DeleteModel(
            name='RejectedDocumentArchive',
        ),
        migrations.RemoveField(
            model_name='documentaccessrule',
            name='employee',
        ),
    ]
