# Generated by Django 4.2.7 on 2025-12-15 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0125_remove_rejecteddocumentarchive_verification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentaccessrule',
            name='access',
            field=models.CharField(choices=[('Access', 'Access'), ('Deny', 'Deny')], default='Access', max_length=50),
        ),
        migrations.AlterField(
            model_name='documentaccessrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_doc_access_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentaccessrule',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_access_rules', to='payrollapp.organization'),
        ),
        migrations.AlterField(
            model_name='documentaccessrule',
            name='role',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='documentaccessrule',
            name='target_employee',
            field=models.ForeignKey(blank=True, help_text='If set, rule applies only to this employee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_access_rules', to='payrollapp.employee'),
        ),
        migrations.AlterField(
            model_name='documentverification',
            name='assigned_role',
            field=models.CharField(blank=True, help_text='Role that performed verification', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='employees', to='payrollapp.roles'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
