# Generated by Django 4.2.7 on 2025-12-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0126_alter_documentaccessrule_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecertifications',
            name='notified_30_days',
            field=models.BooleanField(default=False),
        ),
    ]
