# Generated by Django 4.2.7 on 2025-12-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0127_employeecertifications_notified_30_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecertifications',
            name='notified_after_expiry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeecertifications',
            name='notified_on_expiry',
            field=models.BooleanField(default=False),
        ),
    ]
