# Generated by Django 4.2.7 on 2025-12-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0128_employeecertifications_notified_after_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecertifications',
            name='notified_1_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeecertifications',
            name='notified_7_days',
            field=models.BooleanField(default=False),
        ),
    ]
