# Generated by Django 4.2.7 on 2025-12-29 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0130_remove_employee_reported_to_department_cost_center_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designation',
            old_name='qualifications',
            new_name='job_description',
        ),
        migrations.RenameField(
            model_name='designation',
            old_name='responsibilities',
            new_name='kpis',
        ),
        migrations.RemoveField(
            model_name='department',
            name='cost_center',
        ),
        migrations.RemoveField(
            model_name='location',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='location',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='designation',
            name='kras',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='business_unit',
            field=models.ForeignKey(blank=True, help_text='Business unit this department belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='payrollapp.businessunit'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_head',
            field=models.ForeignKey(blank=True, help_text='Head of the department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='payrollapp.employee'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='Department or team name (e.g. Engineering, Backend Team)', max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='parent_department',
            field=models.ForeignKey(blank=True, help_text='Parent department (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='payrollapp.department'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='band',
            field=models.CharField(blank=True, help_text='Salary range (e.g. 6–10 LPA, 10–14 LPA)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='job_family',
            field=models.CharField(blank=True, help_text='Engineering, HR, Finance, Leadership', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='level',
            field=models.CharField(blank=True, help_text='L1, L2, Senior, Lead, Director, CXO (org-defined)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='name',
            field=models.CharField(help_text='Role name (e.g. Software Engineer, Director, CEO)', max_length=100),
        ),
    ]
