# Generated by Django 4.2.7 on 2025-12-30 04:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0131_rename_qualifications_designation_job_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='timezone',
            new_name='timezone_name',
        ),
        migrations.AddField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
