# Generated by Django 4.2.7 on 2025-12-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0132_rename_timezone_location_timezone_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='child',
            field=models.ManyToManyField(blank=True, null=True, related_name='child', to='payrollapp.childaccount'),
        ),
    ]
