# Generated by Django 4.2.7 on 2025-12-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0133_alter_employee_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('REGULAR', 'Regular Employee'), ('LEADERSHIP', 'Leadership / Executive')], default='REGULAR', max_length=20),
        ),
    ]
