# Generated by Django 4.2.7 on 2026-01-01 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0134_employee_employee_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_type',
        ),
        migrations.CreateModel(
            name='CLevelSeat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('CEO', 'Chief Executive Officer'), ('COO', 'Chief Operating Officer'), ('CTO', 'Chief Technology Officer'), ('CFO', 'Chief Financial Officer'), ('CMO', 'Chief Marketing Officer'), ('CHRO', 'Chief Human Resources Officer'), ('CPO', 'Chief Product Officer'), ('CISO', 'Chief Information Security Officer')], max_length=10)),
                ('title', models.CharField(help_text='Full title of the C-Level role', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Responsibilities at leadership level', null=True)),
                ('is_filled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_level_seats', to='payrollapp.organization')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('parent', 'code')},
            },
        ),
        migrations.CreateModel(
            name='CLevelAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('c_level_seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='payrollapp.clevelseat')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payrollapp.employee')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
