# Generated by Django 4.2.7 on 2026-01-01 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0135_remove_employee_employee_type_clevelseat_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clevelseat',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='clevelseat',
            name='parent',
        ),
        migrations.DeleteModel(
            name='CLevelAssignment',
        ),
        migrations.DeleteModel(
            name='CLevelSeat',
        ),
    ]
