# Generated by Django 4.2.7 on 2026-01-01 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0137_cleveltype_clevelseat_clevelassignment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clevelseat',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='clevelseat',
            name='clevel_type',
        ),
        migrations.RemoveField(
            model_name='clevelseat',
            name='parent',
        ),
        migrations.DeleteModel(
            name='CLevelAssignment',
        ),
        migrations.DeleteModel(
            name='CLevelSeat',
        ),
        migrations.DeleteModel(
            name='CLevelType',
        ),
    ]
