# Generated by Django 4.2.7 on 2026-01-01 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0138_alter_clevelseat_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLevelSeat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cxo_code', models.CharField(help_text='CEO / CFO / CMO etc.', max_length=10)),
                ('seat_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_filled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_level_seats', to='payrollapp.organization')),
            ],
            options={
                'ordering': ['seat_code'],
                'unique_together': {('parent', 'cxo_code')},
            },
        ),
        migrations.CreateModel(
            name='CLevelAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('c_level_seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='payrollapp.clevelseat')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payrollapp.employee')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='reports_to_clevel',
            field=models.ForeignKey(blank=True, help_text='C-Level seat controlling this department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='payrollapp.clevelseat'),
        ),
    ]
