# Generated by Django 4.2.7 on 2026-01-01 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0139_clevelseat_clevelassignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clevelassignment',
            name='end_date',
        ),
    ]
