# Generated by Django 4.2.7 on 2026-01-01 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0140_remove_clevelassignment_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='department',
            name='department_code',
            field=models.CharField(blank=True, help_text='Unique Department ID (e.g. DEPT-ENG-001)', max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this department belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='payrollapp.organization'),
        ),
        migrations.AlterField(
            model_name='department',
            name='business_unit',
            field=models.ForeignKey(blank=True, help_text='Business Unit this department belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='payrollapp.businessunit'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='Department name (Engineering, HR, Backend Team)', max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='parent_department',
            field=models.ForeignKey(blank=True, help_text='Parent department (leave empty for top-level departments)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_departments', to='payrollapp.department'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('organization', 'business_unit', 'name')},
        ),
        migrations.RemoveField(
            model_name='department',
            name='child',
        ),
        migrations.RemoveField(
            model_name='department',
            name='department_head',
        ),
        migrations.RemoveField(
            model_name='department',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='department',
            name='reports_to_clevel',
        ),
    ]
