# Generated by Django 4.2.7 on 2026-01-01 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0141_alter_department_options_department_department_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='reports_to_clevel',
            field=models.ForeignKey(blank=True, help_text='C-Level seat responsible for this department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='payrollapp.clevelseat'),
        ),
    ]
