# Generated by Django 4.2.7 on 2026-01-02 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0143_alter_department_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designation',
            options={'ordering': ['level', 'name'], 'verbose_name': 'Designation', 'verbose_name_plural': 'Designations'},
        ),
        migrations.AddField(
            model_name='designation',
            name='reports_to',
            field=models.ForeignKey(blank=True, help_text='Parent role in org hierarchy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_designations', to='payrollapp.designation'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='band',
            field=models.CharField(blank=True, help_text='Compensation band (e.g. 6–10 LPA)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='child',
            field=models.ForeignKey(blank=True, help_text='Optional child account / sub-organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='payrollapp.childaccount'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete / active flag'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='level',
            field=models.CharField(blank=True, help_text='L1, L2, Senior, Lead, Manager, Director, CXO', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='name',
            field=models.CharField(help_text='Role name (e.g. Software Engineer, Manager, CEO)', max_length=100),
        ),
        migrations.AlterField(
            model_name='designation',
            name='parent',
            field=models.ForeignKey(help_text='Organization this designation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='payrollapp.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='designation',
            unique_together={('parent', 'name')},
        ),
    ]
