# Generated by Django 4.2.7 on 2026-01-05 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0144_alter_designation_options_designation_reports_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_head',
            field=models.ForeignKey(blank=True, help_text='Level-2 Head of this Department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='payrollapp.employee'),
        ),
    ]
