# Generated by Django 4.2.7 on 2026-01-06 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0145_department_department_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='child',
            field=models.ManyToManyField(blank=True, related_name='employees', to='payrollapp.childaccount'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='payrollapp.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='payrollapp.designation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='payrollapp.organization'),
        ),
    ]
