# Generated by Django 4.2.7 on 2026-01-06 10:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0146_alter_employee_child_alter_employee_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('role_type', models.CharField(choices=[('CLEVEL', 'C-Level'), ('DEPARTMENT', 'Department'), ('ROLE', 'Role')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_roles', to='payrollapp.childaccount')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_roles', to='payrollapp.organization')),
                ('parent_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='payrollapp.orgrole')),
            ],
        ),
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='payrollapp.employee')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='payrollapp.orgrole')),
            ],
        ),
    ]
