# Generated by Django 4.2.7 on 2026-01-06 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0147_orgrole_alter_roles_name_roleassignment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roles',
            unique_together={('parent', 'child', 'name')},
        ),
    ]
