# Generated by Django 4.2.7 on 2026-01-06 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0148_alter_roles_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleassignment',
            name='is_primary',
        ),
        migrations.AddField(
            model_name='orgrole',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orgrole',
            name='parent_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='payrollapp.orgrole'),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payrollapp.employee'),
        ),
        migrations.AlterUniqueTogether(
            name='orgrole',
            unique_together={('parent', 'name')},
        ),
        migrations.RemoveField(
            model_name='orgrole',
            name='child',
        ),
        migrations.RemoveField(
            model_name='orgrole',
            name='code',
        ),
        migrations.RemoveField(
            model_name='orgrole',
            name='role_type',
        ),
    ]
