# Generated by Django 4.2.7 on 2026-01-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0149_remove_roleassignment_is_primary_orgrole_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='matrix_managers',
            field=models.ManyToManyField(blank=True, related_name='matrix_reportees', to='payrollapp.employee'),
        ),
    ]
