# Generated by Django 4.2.7 on 2026-01-08 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0150_employee_matrix_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleassignment',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='roleassignment',
            name='role',
        ),
        migrations.DeleteModel(
            name='OrgRole',
        ),
        migrations.DeleteModel(
            name='RoleAssignment',
        ),
    ]
