
# Generated by Django 4.2.7 on 2026-01-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0151_remove_roleassignment_employee_and_more'),
    ]

    operations = [
    migrations.AlterField(
        model_name='designation',
        name='level',
        field=models.TextField(null=True, blank=True),
    ),
]
