# Generated by Django 4.2.7 on 2026-01-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0153_alter_designation_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='level',
            field=models.CharField(blank=True, choices=[('L0', 'L0 – Business Owner'), ('L1', 'L1 – CEO'), ('L2', 'L2 – C-Level Executive'), ('L3', 'L3 – Department'), ('L4', 'L4 – Department Head'), ('L5', 'L5 – Manager'), ('L6', 'L6 – Team Lead'), ('L7', 'L7 – Individual Contributor')], help_text='Org hierarchy level (L0–L7)', max_length=30, null=True),
        ),
    ]
