# Generated by Django 4.2.7 on 2026-01-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0154_alter_designation_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='level',
            field=models.TextField(blank=True, null=True),
        ),
    ]
