# Generated by Django 4.2.7 on 2026-01-08 09:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0156_alter_designation_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_type', models.CharField(choices=[('MANUAL', 'Manual'), ('MONTHLY', 'Monthly'), ('PROMOTION', 'Promotion'), ('TRANSFER', 'Transfer')], default='MANUAL', max_length=20)),
                ('tree_data', models.JSONField()),
                ('matrix_data', models.JSONField()),
                ('analytics_data', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='payrollapp.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
