# Generated by Django 4.2.7 on 2026-01-08 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0157_orgsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsnapshot',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payrollapp.employee'),
        ),
        migrations.AlterField(
            model_name='orgsnapshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orgsnapshot',
            name='snapshot_type',
            field=models.CharField(choices=[('AUTO', 'Auto'), ('MANUAL', 'Manual')], default='MANUAL', max_length=10),
        ),
    ]
