# Generated by Django 4.2.7 on 2026-01-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0158_orgsnapshot_triggered_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgsnapshot',
            name='analytics_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='orgsnapshot',
            name='matrix_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='orgsnapshot',
            name='tree_data',
            field=models.JSONField(default=list),
        ),
    ]
