# Generated by Django 4.2.7 on 2026-01-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0159_alter_orgsnapshot_analytics_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='org_structure_updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Updated whenever org structure changes'),
        ),
    ]
