# Generated by Django 4.2.7 on 2026-01-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0160_organization_org_structure_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='org_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
